[package]
name = "rust_ob"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rb_tree = "0.5.0"
rust_decimal = "1.32.0"
